# Generated by Django 3.1.2 on 2021-05-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Km',
            field=models.IntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='product',
            name='Owners',
            field=models.IntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='product',
            name='Year',
            field=models.IntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
