# Generated by Django 3.1.2 on 2021-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210518_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='g',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Km',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Owners',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Year',
            field=models.CharField(default='Null', max_length=4),
        ),
    ]
