# Generated by Django 3.1.2 on 2021-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210518_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('des', models.CharField(default='Null', max_length=200)),
                ('location', models.CharField(default='Null', max_length=20)),
                ('Year', models.CharField(default='Null', max_length=4)),
                ('g', models.BooleanField(blank=True, default=False, null=True)),
                ('car', models.CharField(max_length=200)),
            ],
        ),
    ]
