# Generated by Django 3.1.2 on 2021-05-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_parts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.AddField(
            model_name='product',
            name='car',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
