# Generated by Django 3.1.2 on 2021-05-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210519_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalprice',
            field=models.FloatField(default=0.0),
        ),
    ]
