# Generated by Django 3.1.2 on 2021-05-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='totalprice',
        ),
        migrations.AddField(
            model_name='product',
            name='totalprice_for_rent',
            field=models.FloatField(default=500.0),
        ),
    ]
