# Generated by Django 3.1.2 on 2021-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210519_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='totalprice_for_rent',
        ),
        migrations.AddField(
            model_name='product',
            name='totalprice',
            field=models.FloatField(default=1234500.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=500.0),
        ),
    ]
