# Generated by Django 3.1.2 on 2021-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210605_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
