# Generated by Django 3.1.2 on 2021-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210605_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Year',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='car',
            field=models.CharField(default='Not', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(default='Null', max_length=25),
        ),
    ]
