# Generated by Django 3.1.2 on 2021-06-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
